[package]
name = "rustfulapi"
version = "0.1.0"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]

[dependencies.log]
version = "0.3.5"

[dependencies.env_logger]
version = "0.3.2"

[dependencies.rustful]
version = "0.6"
default-features = false
features = ["rustc_json_body", "multipart"]
