apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: colemickens/dotkube-api-service:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: colemickens/dotkube-api-nginx:latest
        ports:
        - containerPort: 80
