apiVersion: v1
kind: ReplicationController
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: colemickens/dotkube-db:latest
        ports:
        - containerPort: 80
