apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: colemickens/dotkube-frontend:latest
        ports:
        - containerPort: 80
