apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE
          value: azure
        - name: REGISTRY_STORAGE_AZURE_ACCOUTNAME
          value: /azure-registry-storage-secret/azure_storage_account
        - name: REGISTRY_STORAGE_AZURE_ACCOUNTKEY
          value: /azure-registry-storage-secret/azure_storage_key
        - name: REGISTRY_STORAGE_AZURE_CONTAINER
          value: /azure-registry-storage-secret/azure_storage_container
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        volumeMounts:
        - name: gcs-key
          mountPath: /gcs
      volumes:
      - name: azure-registry-storage-secret
        secret:
          secretName: azure-registry-storage-secret
